version: '3.4'

services:
  nosql.data:
    image: mongo

  catalog.api:
    image: ymicroservices/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - nosql.data